/**
 * This code was autogenerated from a Postman source
 */
const http = require('http');
const PORT = process.env.PORT || 4500;

const server = http.createServer((req, res) => {
  const url = new URL(req.url || '', 'http://localhost');
  const pathname = url.pathname;

  // @endpoint POST /{{api_version}}/auth/login
  if (req.method === 'POST' && /^\/([^/]+)\/auth\/login$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "401 - Credenciais inválidas" — when x-mock-response-code: 401
    if (requestedStatusCode === '401') {
      res.writeHead(401, { "Content-Type": "application/json" });
      return res.end(JSON.stringify({ "error": "invalid_credentials", "message": "E-mail ou senha inválidos." }));
    }

    // "200 - Login bem-sucedido" — default
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "access_token": "eyJhbGciOiJIUzI1NiJ9.mock.token", "refresh_token": "9f2c9a3e-6e2a-4e9b-9a3e-6e2a4e9b9a3e", "expires_in": 3600 }));
  }

  // @endpoint POST /{{api_version}}/auth/refresh
  if (req.method === 'POST' && /^\/([^/]+)\/auth\/refresh$/.test(pathname)) {
    // Preenchido à mão a partir do schema TokenPair de postman/specs/openapi.yaml
    // (não havia exemplo salvo nesta requisição da collection).
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "access_token": "eyJhbGciOiJIUzI1NiJ9.mock.refreshed", "refresh_token": "9f2c9a3e-6e2a-4e9b-9a3e-6e2a4e9b9a3e", "expires_in": 3600 }));
  }

  // @endpoint POST /{{api_version}}/auth/logout
  if (req.method === 'POST' && /^\/([^/]+)\/auth\/logout$/.test(pathname)) {
    // Spec define 204 sem corpo para logout.
    res.writeHead(204);
    return res.end();
  }

  // @endpoint GET /{{api_version}}/owners
  if (req.method === 'GET' && /^\/([^/]+)\/owners$/.test(pathname)) {
    // Preenchido a partir do schema OwnerList de postman/specs/openapi.yaml.
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "items": [{ "id": "6f1a2b3c-owner", "name": "Maria Souza", "email": "maria.souza@example.com", "phone": "+55 11 99999-0000", "createdAt": "2026-08-11T12:00:00Z" }], "page": 1, "pageSize": 20, "total": 1 }));
  }

  // @endpoint POST /{{api_version}}/owners
  if (req.method === 'POST' && /^\/([^/]+)\/owners$/.test(pathname)) {
    res.writeHead(201, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "id": "6f1a2b3c-owner", "name": "Maria Souza", "email": "maria.souza@example.com", "phone": "+55 11 99999-0000", "createdAt": "2026-08-11T12:00:00Z" }));
  }

  // @endpoint GET /{{api_version}}/owners/:ownerId
  if (req.method === 'GET' && /^\/([^/]+)\/owners\/([^/]+)$/.test(pathname)) {
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "id": "6f1a2b3c-owner", "name": "Maria Souza", "email": "maria.souza@example.com", "phone": "+55 11 99999-0000", "createdAt": "2026-08-11T12:00:00Z" }));
  }

  // @endpoint DELETE /{{api_version}}/owners/:ownerId
  if (req.method === 'DELETE' && /^\/([^/]+)\/owners\/([^/]+)$/.test(pathname)) {
    res.writeHead(204);
    return res.end();
  }

  // @endpoint GET /{{api_version}}/pets
  if (req.method === 'GET' && /^\/([^/]+)\/pets$/.test(pathname)) {
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "items": [{ "id": "pet-001", "name": "Rex", "species": "dog", "breed": "Labrador", "ownerId": "6f1a2b3c-owner" }], "page": 1, "pageSize": 10, "total": 1 }));
  }

  // @endpoint POST /{{api_version}}/pets
  if (req.method === 'POST' && /^\/([^/]+)\/pets$/.test(pathname)) {
    res.writeHead(201, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "id": "pet-001", "name": "Rex", "species": "dog", "breed": "Labrador", "birthDate": "2022-03-15", "ownerId": "6f1a2b3c-owner", "createdAt": "2026-08-11T12:05:00Z" }));
  }

  // @endpoint GET /{{api_version}}/pets/:petId
  if (req.method === 'GET' && /^\/([^/]+)\/pets\/([^/]+)$/.test(pathname)) {
    res.writeHead(404, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "error": "not_found", "message": "Pet não encontrado." }));
  }

  // @endpoint PUT /{{api_version}}/pets/:petId
  if (req.method === 'PUT' && /^\/([^/]+)\/pets\/([^/]+)$/.test(pathname)) {
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "id": "pet-001", "name": "Rex", "species": "dog", "breed": "Labrador Retriever", "weightKg": 28.5, "ownerId": "6f1a2b3c-owner" }));
  }

  // @endpoint DELETE /{{api_version}}/pets/:petId
  if (req.method === 'DELETE' && /^\/([^/]+)\/pets\/([^/]+)$/.test(pathname)) {
    res.writeHead(204);
    return res.end();
  }

  // @endpoint GET /{{api_version}}/appointments
  if (req.method === 'GET' && /^\/([^/]+)\/appointments$/.test(pathname)) {
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "items": [{ "id": "appt-500", "petId": "pet-001", "vetId": "vet-010", "scheduledAt": "2026-08-20T14:30:00Z", "reason": "Consulta de rotina", "status": "scheduled" }] }));
  }

  // @endpoint POST /{{api_version}}/appointments
  if (req.method === 'POST' && /^\/([^/]+)\/appointments$/.test(pathname)) {
    res.writeHead(201, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "id": "appt-500", "petId": "pet-001", "vetId": "vet-010", "scheduledAt": "2026-08-20T14:30:00Z", "status": "scheduled" }));
  }

  // @endpoint DELETE /{{api_version}}/appointments/:appointmentId
  if (req.method === 'DELETE' && /^\/([^/]+)\/appointments\/([^/]+)$/.test(pathname)) {
    res.writeHead(204);
    return res.end();
  }

  // @endpoint GET /health
  if (req.method === 'GET' && pathname === '/health') {
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ "status": "ok", "uptimeSeconds": 123456 }));
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Endpoint not defined' }));
});

server.listen(PORT);
